version: '3.8'

services:
  config-server:
    image: config-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/soknem/config-server
    networks:
      - config-network

networks:
  config-network:
    driver: bridge
